# Generated by Django 4.2.18 on 2026-03-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('program', models.CharField(max_length=100)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], max_length=1)),
                ('validity_status', models.CharField(choices=[('NOT_VERIFIED', 'Not Verified'), ('VERIFIED', 'Verified'), ('INVALID', 'Invalid')], default='NOT_VERIFIED', max_length=20)),
                ('photo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
