services:
  db:
    image: postgres:18
    environment:
      POSTGRES_DB: thesis_qr
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mizijen
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thesis_qr"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build: ./backend
    environment:
      DJANGO_SECRET_KEY: "dev-only-change-me"
      DJANGO_DEBUG: "1"
      DATABASE_URL: "postgresql://postgres:mizijen@db:5432/thesis_qr"
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    

  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: "http://192.168.1.22:8000" #change as needed to match backend's IP and port
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0

volumes:
  pgdata: