# Generated by Django 4.2.18 on 2026-03-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifid', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='scanned_at',
            new_name='timestamp',
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='gate',
            field=models.CharField(default='Main Gate', max_length=50),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='qr_payload',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='reason',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
