# Generated by Django 4.2 on 2026-03-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifid', '0002_delete_student_rename_scanned_at_scanlog_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanlog',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='scanlog',
            old_name='student_id',
            new_name='id_number',
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='gate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scanlog',
            name='year_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
