# Generated by Django 4.2 on 2026-03-21 02:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('verifid', '0003_rename_timestamp_scanlog_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(default='main_window', max_length=100, unique=True)),
                ('gate', models.CharField(default='Main Gate', max_length=50)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
