# Generated by Django 4.2 on 2026-03-28 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('verifid', '0004_scannerstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRRawScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_qr_data', models.TextField()),
                ('qr_timestamp', models.DateTimeField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('program', models.CharField(blank=True, max_length=100, null=True)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('is_valid_format', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('scan_log', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_scan', to='verifid.scanlog')),
            ],
        ),
    ]
