# Generated by Django 4.2 on 2026-03-28 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('verifid', '0005_qrrawscan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrrawscan',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='qrrawscan',
            name='is_valid_format',
        ),
        migrations.RemoveField(
            model_name='qrrawscan',
            name='qr_timestamp',
        ),
        migrations.RemoveField(
            model_name='qrrawscan',
            name='raw_qr_data',
        ),
        migrations.RemoveField(
            model_name='qrrawscan',
            name='scan_log',
        ),
    ]
